# Generated by Django 4.2.19 on 2025-03-31 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0150_alter_contest_private_contestants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='api_token',
        ),
    ]
