# Generated by Django 4.2.20 on 2025-03-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0150_problem_difficulty_alter_contest_private_contestants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='Easy', max_length=10),
        ),
    ]
