# Generated by Django 4.2.20 on 2025-03-20 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0154_alter_problem_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='difficulty',
        ),
    ]
