# Generated by Django 4.2.20 on 2025-03-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0155_remove_problem_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(max_length=20, unique=True)),
            ],
        ),
    ]
