# Generated by Django 4.2.20 on 2025-03-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0157_problem_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='difficulty'),
        ),
    ]
