# Generated by Django 4.2.20 on 2025-03-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0158_alter_problem_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
    ]
