# Generated by Django 4.2.20 on 2025-03-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0159_alter_problem_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', help_text='A short, unique code for the problem, used in the URL after /problem/', max_length=10, verbose_name='problem code'),
        ),
    ]
