# Generated by Django 4.2.20 on 2025-04-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0151_remove_profile_api_token'),
        ('judge', '0160_alter_problem_difficulty'),
    ]

    operations = [
    ]
