# Generated by Django 4.2.20 on 2025-04-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0161_merge_20250409_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', help_text='The problem difficulty level', max_length=10, verbose_name='problem difficulty'),
        ),
        migrations.AlterField(
            model_name='problemtestcase',
            name='is_pretest',
            field=models.BooleanField(default=False, verbose_name='case is pretest?'),
        ),
    ]
