# Generated by Django 4.2.20 on 2025-04-30 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0162_alter_problem_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='class_required',
        ),
        migrations.RemoveField(
            model_name='organizationrequest',
            name='request_class',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
