# Generated by Django 4.2.20 on 2025-05-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0161_merge_20250413_1350'),
        ('judge', '0163_alter_profile_timezone'),
        ('judge', '0163_remove_contest_classes_and_more'),
    ]

    operations = [
    ]
