# Generated by Django 4.2.20 on 2025-05-25 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judge', '0163_remove_contest_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='blog_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='subscribers'),
        ),
    ]
