# Generated by Django 4.2.20 on 2025-05-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0164_merge_20250520_1446'),
        ('judge', '0165_contestfollow'),
    ]

    operations = [
    ]
