# Generated by Django 4.2.20 on 2025-06-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0166_merge_0164_merge_20250520_1446_0165_contestfollow'),
        ('judge', '0166_user_fk_cascade'),
    ]

    operations = [
    ]
